local echo = AchaeaChatTabs.helpers.echo
local validOptions = table.keys(AchaeaChatTabs.config)
table.sort(validOptions)
local validOptionsString = table.concat(validOptions, ", ")
echo("Usage information for changing act colors")
echo()
echo("act color <option> <color>")
echo("Color can be anything you would use in CSS, such as 'rgb(128,128,128)', '#888888', or 'grey'")
echo("examples:")
echo("  * act color activeBorder goldenrod")
echo("    * changes the border around the active tab to goldenrod")
echo("  * act color activeColor #00ff00")
echo("    * changes the color of the active tab to green")
echo()
echo("Valid options are " .. validOptionsString)
echo("Remember to use 'act save' to make your changes permanent, or 'act load' to undo them and reset back to what you previously saved.")